package ExceptionHandlingPract;

public class Main {
public static void main(String[] args) {
//        try {
//            int[] arr = new int[5];
//            arr[10] = 10;
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println("ArrayIndexOutOfBoundsException");
//        } catch (Exception e) {
//            System.out.println("Exception");
//        } finally {
//            System.out.println("Finally");
//        }

//    System.out.println(1/0);
    System.out.println("The is the end of the program");
    }
}
